### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by MonoidMusician** [mikesol/wagsi#13]
After pulling the latest, it isn't working for me anymore for some reason.

Ran `npm install` to reinstall dependencies (even after nuking `node_modules`) and then `npm run start`. I'm pretty sure this is how I got this working earlier (November 11th).

The first problem is that I don't hear audio, after pressing start audio and waiting for a while.

The second problem is that the code displayed in the browser does not update, even though the other parts of the process seem to be working behind the scenes:

The PS seems to compile fine, and I see normal console output when I save the live-coding file:
```
ℹ ｢wdm｣: Compiling...
ℹ ｢wdm｣: assets by status 9.53 MiB [cached] 1 asset
cached modules 8.61 MiB (javascript) 27.1 KiB (runtime) [cached] 652 modules
./src/LiveCodeHere/Wagged.purs 5.8 KiB [built]
webpack 5.64.3 compiled successfully in 300 ms
ℹ ｢wdm｣: Compiled successfully.
```

It even makes its way to normal-looking JS console output:
```
index.js:24 Found an initial wag 🐶
index.js:29 Found initial code 📦
log.js:24 [HMR] Waiting for update signal from WDS...
index.js:49 [WDS] Hot Module Replacement enabled.
index.js:53 [WDS] Live Reloading enabled.
2index.js:56 [WDS] App updated. Recompiling...
reloadApp.js:19 [WDS] App hot update...
log.js:24 [HMR] Checking for updates on the server...
log.js:24 [HMR] Updated modules:
log.js:24 [HMR]  - ./src/LiveCodeHere/Wagged.purs
log.js:24 [HMR] App is up to date.
```

I even see network requests for the right sound files, but I don't hear anything. The tab is unmuted and I see no errors. Strange.

**Comment by mikesol** [comment]
I believe this is now fixed with https://github.com/mikesol/wagsi/commit/23be378233de07624a1052529bbbcabf98384ef0. If so, please feel free to close the issue, otherwise I will keep it open!
